apiVersion: apps/v1
kind: Deployment
metadata:
  name: graf-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: graf
  template:
    metadata:
      labels:
        name: graf
    spec:
      containers:
      - name: graf
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: graf-storage
          mountPath: /var/lib/grafana
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: graf-storage
        persistentVolumeClaim:
          claimName: graf-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: graf-nodeport
spec:
  type: NodePort
  selector:
    name: graf
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30030


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

