apiVersion: v1
kind: Service
metadata:
  name: prom-node
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30099
  selector:
    app: prom-pod

---

apiVersion: v1
kind: Service
metadata:
  name: prom-clusterip
spec:
  type: ClusterIP
  selector:
    app: prom-pod
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9090
    targetPort: 9090

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-pod
  template:
    metadata:
      labels:
        app: prom-pod
    spec:
      containers:
      - name: prom-pod
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prom-vol
          mountPath: /prometheus
        - name: prom-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prom-vol
        persistentVolumeClaim:
          claimName: prom-pvc
      - name: prom-config
        configMap:
          name: prom-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
    - job_name: 'prom'
      static_configs:
      - targets: ['10.102.185.239:9090']
    - job_name: 'nginx'
      static_configs:
      - targets: ['10.106.200.70:9100']