apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-at
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx-pod
  ports:
  - name: nginx-metrics
    protocol: TCP
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-metrics
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
  - protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 30091