apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: nginx-vol
    persistentVolumeClaim:
      claimName: nginx-vol-claim
  containers:
  - name: nginx-tp2
    image: nginx:1.19.10
    volumeMounts:
      - name: nginx-vol
        mountPath:   /Users/Lucas/Documents/codes/bloco microservicos/kubernetes/volumes
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
