apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
spec:
  type: ClusterIP
  selector:
    app: streaming-pod
  ports:
  - port: 5115  
    targetPort: 5115

---
apiVersion: v1
kind: Pod
metadata:
  name: streaming-pod
spec:
  containers:
  - name: streaming-pod
    image: miojoinfnet/spoofystreamingapi:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 5115

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    app: user-pod
  ports:
  - nodePort: 32117
    port: 7211
    targetPort: 7211

--- 
apiVersion: v1
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
  - name: user-pod
    image: miojoinfnet/spoofyuserapi:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 7211