apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
spec:
  type: ClusterIP
  clusterIP: 10.103.137.250
  selector:
    tier: stream
  ports:
  - port: 5115  
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: streaming-pod
  labels:
    tier: stream
spec:
  containers:
  - name: streaming-con
    image: miojoinfnet/spoofystreamingapi:p-80-clust-ip
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    tier: user
  ports:
<<<<<<< HEAD
  - nodePort: 32117
    port: 7211
    targetPort: 80
=======
  - nodePort: 31127
    port: 80
>>>>>>> 62231e348013c45894ea3950064e9c07e184f1f1

--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-replica
  labels:
    tier: user
spec:
<<<<<<< HEAD
  containers:
  - name: user-pod
    image: miojoinfnet/spoofyuserapi:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
=======
  replicas: 4
  selector:
    matchLabels:
      tier: user
  template:
    metadata:
      labels:
        tier: user
    spec:
      containers:
      - name: user-con
        image: miojoinfnet/spoofyuserapi:p-80-clust-ip
        ports:
        - containerPort: 80
      - name: monitoring
        image: registry.k8s.io/busybox
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 4
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
>>>>>>> 62231e348013c45894ea3950064e9c07e184f1f1
