apiVersion: v1
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
  - name: user-pod
    image: miojoinfnet/spoofyuserapi
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 7211