apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
spec:
  type: ClusterIP
  clusterIP: 10.103.137.250
  selector:
    tier: stream
  ports:
  - port: 5115  
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: streaming-pod
  labels:
    tier: stream
spec:
  containers:
  - name: streaming-con
    image: miojoinfnet/spoofystreamingapi:p-80-clust-ip
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    tier: user
  ports:
  - nodePort: 31127
    port: 80

--- 
apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    tier: user
spec:
  containers:
  - name: user-con
    image: miojoinfnet/spoofyuserapi:p-80-clust-ip
    ports:
    - containerPort: 80