apiVersion: v1
kind: Service
metadata:
  name: streaming-svc
spec:
  type: ClusterIP
  clusterIP: 10.103.137.250
  selector:
    tier: stream
  ports:
  - port: 5115  
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: streaming-pod
  labels:
    tier: stream
spec:
  containers:
  - name: streaming-con
    image: miojoinfnet/spoofystreamingapi:p-80-clust-ip
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    tier: user
  ports:
  - nodePort: 31127
    port: 80

--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-replica
  labels:
    tier: user
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: user
  template:
    metadata:
      labels:
        tier: user
    spec:
      containers:
      - name: user-con
        image: miojoinfnet/spoofyuserapi:p-80-clust-ip
        ports:
        - containerPort: 80
      - name: monitoring
        image: registry.k8s.io/busybox
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 4
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5